language: php
sudo: false
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

services: redis-server

before_script:
  - phpenv config-rm xdebug.ini
  - echo "extension = <extension>.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit

matrix:
  fast_finish: true